name: manualAlign
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - scipy
  - scikit-image
  - pillow
  - tifffile
  - pyside6
  - pyinstaller        # available on conda-forge
  - pip:
    - opencv-python-headless>=4.8.0